
version: 0.1
phases:
  install:
    runtime-versions:
        ruby: 2.6
    commands:
      - bundle install
  build:
    commands:
      - ruby ./hellotest.rb
  post_build:
    commands:
      - echo Build completed on $(date)
