
version: 0.2
phases:
  install:
    runtime-versions:
        ruby: 2.6
    commands:
      - gem install bundler:2.0.1
      - bundle install
  build:
    commands:
      - ruby ./hellotest.rb
  post_build:
    commands:
      - echo Build completed on $(date)
